### ISSUE TITLE
training time for REDSwith 600K

### ISSUE THREAD

**Issue by caide199212** [kai422/IART#1]
Nice work!!
May I ask how long did it take to train REDS with IART as in the `IART_REDS_N16_600K.yml`

**Comment by kai422** [comment]
Hi, 

The training time on RTX-A5000 for IART is 6.7ms/iter for 16 input training frames and 2.6ms/iter for 6 input training frames. For comparison, the training time for PSRT-recurrent on RTX-A5000 for IART is 6.4ms/iter for 16 input training frames and 2.5ms/iter for 6 input training frames.
As our GPU type is not that common. PSRT takes 18 days on 8 A100. you can expect the similar training time.

Regards,
Kai
