### ISSUE TITLE
Question about testing: from archs.iart_arch import IART ModuleNotFoundError: No module named 'archs'

### ISSUE THREAD

**Issue by chahu-12** [kai422/IART#15]
Nice work!
How can i solve this prroblem.

**Comment by hzhXue** [comment]
How do you solve this problem?

**Comment by chahu-12** [comment]
i&nbsp; ran in pycharm,not cmd
&nbsp;


小茶壶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月11日(星期三) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [kai422/IART] Question about testing: from archs.iart_arch import IART ModuleNotFoundError: No module named &#39;archs&#39; (Issue #15)














 
How do you solve this problem?

**Comment by hzhXue** [comment]
thanks

**Comment by hzhXue** [comment]
I want to ask you some questions?which version did you pip about the requirements.txt

**Comment by chahu-12** [comment]
> I want to ask you some questions?which version did you pip about the requirements.txt

![image](https://github.com/user-attachments/assets/a74462ae-6a41-43da-9c22-9e486b2918f2)

**Comment by hzhXue** [comment]
Did you run successfully?
