### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by zgq91** [kai422/IART#2]
Hi
     Thanks for sharing. How much time does the model inference take?

**Comment by kai422** [comment]
Hi Zgq91!

Thank you for your interest. For information on the inference time, please refer to our recently [updated paper](https://github.com/kai422/IART/blob/main/arxiv.pdf).

Regards,
Kai

**Comment by foxbeing7** [comment]
i wrote a script to infer a list of 183 images of 480*240. it took 634s.

**Comment by kai422** [comment]
Hi foxbeing7,

What type of GPU are you currently using?

Regards,
Kai

**Comment by foxbeing7** [comment]
> Hi foxbeing7,
> 
> What type of GPU are you currently using?
> 
> Regards, Kai

Hi , I'm using tesla V100 with 32G gpu memory.
BTW, is there any advices for speeding up I/O ? 
Thanks for your reply.

**Comment by kai422** [comment]
Hi, in the paper, I used the RTX A5000, which is based on the Ampere architecture with 8,192 CUDA cores and a clock speed of 1695 MHz. The inference speed is 2.1s per image.

The RTX V100 is an older generation (Volta) with 5,120 cores and a 1530 MHz clock speed. The expected inference speed would roughly be 2.1 * (1695/1530) * (8192/5120) = 3.72s per image. I think this aligns with your results.

For speeding up I/O for training, you can consider: 1) loading all data into memory before training; 2) using [lmdb](https://github.com/caojiezhang/VSR-Transformer/blob/main/docs/DatasetPreparation.md) for training; 3) using an SSD. 

I didn't experience any bottlenecks with I/O during my training.

Regards,
Kai

**Comment by foxbeing7** [comment]
> Hi, in the paper, I used the RTX A5000, which is based on the Ampere architecture with 8,192 CUDA cores and a clock speed of 1695 MHz. The inference speed is 2.1s per image.
> 
> The RTX V100 is an older generation (Volta) with 5,120 cores and a 1530 MHz clock speed. The expected inference speed would roughly be 2.1 * (1695/1530) * (8192/5120) = 3.72s per image. I think this aligns with your results.
> 
> For speeding up I/O for training, you can consider: 1) loading all data into memory before training; 2) using [lmdb](https://github.com/caojiezhang/VSR-Transformer/blob/main/docs/DatasetPreparation.md) for training; 3) using an SSD.
> 
> I didn't experience any bottlenecks with I/O during my training.
> 
> Regards, Kai

I will try it later, thanks for the advice

**Comment by Platorius** [comment]
And what is the inference Speed, when you upscale real-world Content, which is not 240p ?

What if you wan't to upscale 720p content? 720p has 9 times more pixel. Does that mean, inference time is 9 times higher and therefore ~18 secondens for one single frame with an RTX A5000 ? So basically 0.056FPS ?

**Comment by kai422** [comment]
> And what is the inference Speed, when you upscale real-world Content, which is not 240p ?
> 
> What if you wan't to upscale 720p content? 720p has 9 times more pixel. Does that mean, inference time is 9 times higher and therefore ~18 secondens for one single frame with an RTX A5000 ? So basically 0.056FPS ?

It will likely cost that much time. Sometimes the bottleneck is at the pipeline, so I guess it will not scale linearly. Nevertheless, I will make a demo code and try it on 720p content shortly.
