### ISSUE TITLE
Make own video be clear!

### ISSUE THREAD

**Issue by 0Godness** [kai422/IART#4]
Thanks for your nice work and code! I want to know how to make own video be clear. It seems the test code just for the metric calculation.

**Comment by kai422** [comment]
Hi,

I will try to make a demo code where you can work on your own video shortly. :) Thanks for your advice! 

Regards,
Kai

**Comment by 0Godness** [comment]
> Hi,
> 
> I will try to make a demo code where you can work on your own video. :) Thanks for your advice!
> 
> Regards, Kai

That's so nice! Thanks a lot for that, hoping get the demo code soon.
