### ISSUE TITLE
关于test的问题

### ISSUE THREAD

**Issue by summerwang0806** [kai422/IART#5]
![image](https://github.com/kai422/IART/assets/90956230/80589b00-67dc-41cf-a963-c8b60fabd043)
我需要在后面加入X4才可以test
否则会报错，如果遇见相同问题的朋友或许可以试一下

**Comment by kai422** [comment]
Hi,
Thanks for pointing that out! The 'X4' could change depending on where you download the dataset. Just adjust the folder name to match your directory.
