### ISSUE TITLE
Vid4 Inference Results

### ISSUE THREAD

**Issue by DachunKai** [kai422/IART#6]
Hi, could you kindly provide the inference results for the Vid4 dataset, similar to how you provided them for the REDS4 dataset?

**Comment by kai422** [comment]
Hi please check the results under `demo/Vid4_BI_results`, you can also run it by yourself with `python demo.py`.

**Comment by DachunKai** [comment]
Thanks. Could you kindly upload the inference results for the REDS4 dataset?
