### ISSUE TITLE
Degradation code

### ISSUE THREAD

**Issue by Ar0Kim** [kai422/IART#8]
Hi, thank you for sharing your code. I have a question: could you please share the degradation code and the reference sites you used for creating BD and BI degradations to make low resolution images? I would like to use your code to train my own model. Thank you!

**Comment by kai422** [comment]
Hi, we use matlab for degradation, I will organize the code and upload it shortly.

**Comment by Ar0Kim** [comment]
thanks for the reply, looking forward to it :)

**Comment by kai422** [comment]
Hi please check the matlab code for BD degradation under the dataset folder. For BI degradation, just change the degradation code to `lq = imresize(gt, 1/scale, 'bicubic')`.
